### ISSUE TITLE
Hilla multi-module engine (experimental)

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#123]
## Background

For generating TypeScript endpoint and data definitions based on Java endpoints, Hilla historically used a combination of a Java source code parser, and template based TypeScript code generator. We faced the following limitations of those:

- Hard to support of multi-module applications with endpoints defined in dependency modules, for example, in .jar, as Java source code is generally not available for those.
- Hard to support JVM languages other than Java, as each language requires a different parser.
- Hard to extend the code generator. The template files are complex, and are not well suited for access by multiple parties, such as plugins.

As a better approach for future, we chose to go with a class file parser and an AST based TypeScript generator.

## Use cases

- As a developer, I want to reuse the endpoints defined in Hilla application B in another Hilla application A.
- As a developer, I want to share a library of Hilla endpoints, distributed in a .jar.

## Acceptance criteria

- [x] A feature flag that switches from source-based to multi-module engine in a Hilla application
- [ ] Apart from known limitations listed below, all features of the source-based generator are supported, including
  - [x] `@Endpoint` annotation
  - [ ] `@EndpointExposed` annotation
  - [x] Class remapping, for example: `Pageable`, `UUID`, `Flux`, `Mono`.
  - [x] Form model validation definitions
  - [x] `@Nonnull` and `@NonNullApi`
  - [ ] `@JsonIgnore`
- [x] Hilla integration tests are green with both source-based and multi-module engine
- [x] Parser consists of several feature-based plugins
- [x] Generator consists of several feature-based plugins
- [x] Supports the Hilla CRM tutorial application, the feature flag does not break any application features
- [ ] Supports the Hilla Starter application, the feature flag does not break any application features

## General criteria

 - [ ] APIs reviewed
 - [ ] Performance (should not have noticeable negative effect on production build and dev mode startup time)
 - [ ] UX/DX tests in Alpha
 - [ ] Documentation (a tutorial article on using the multi-module engine)
 - [ ] How to test?
 - [ ] Limitations:
  - Does not support Javadoc class and method descriptions

**Comment by Haprog** [comment]
Take #125 as a use case example which could be used as inspiration on what type of hooks are needed to be able to support that kind of implementation.
