### ISSUE TITLE
Object based data models

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#1903]
### Discussed in https://github.com/vaadin/hilla/discussions/1634

Following the aforementioned RFC and the discussion, let us replace the class-based models with the object based design. 

This is a big change. I would suggest to break it down onto steps, roughly:

- [ ] Add a separate package `packages/ts/model` with the model primitives and builder APIs.
- [ ] Add a generator plugin to emit models in the object-based format, which would initially coexisting with the class-based models.
- [ ] Update the `form` and `react-form` libraries to use the object-based models.
- [ ] Update the CRUD helpers to use the object-based models.
- [ ] Remove the class-based models generator.
- [ ] Update documentation and example apps.
