### ISSUE TITLE
Update Hilla release checklist

### ISSUE THREAD

**Issue by platosha** [vaadin/hilla#223]
- [ ] Update a checklist for releasing Hilla.
- [ ] Make sure to include all the relevant parts.
- [ ] Share and discuss with the platform team.
